[project]
name = "mcp-server-formatter"
version = "0.1.0"
description = "MCP server with Black code formatting functionality"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.4.0",
    "black>=24.2.0",
]
